import numpy as np
import matplotlib.pyplot as plt

# Load CSV generated by ngspice
data = np.loadtxt('output.csv', delimiter=' ', skiprows=1)

time = data[:, 0]
voltage = data[:, 1]

plt.figure(figsize=(8,5))
plt.plot(time, voltage, label="V(out)")
plt.xlabel("Time (s)")
plt.ylabel("Voltage (V)")
plt.title("NGSpice Transient Simulation")
plt.grid()
plt.legend()
plt.savefig("plot.png")
print("Plot saved as plot.png")
