name: Run NGSpice Simulation

on:
  push:
    paths:
      - '**.cir'
      - '**.py'
      - '**.sh'
  pull_request:
    paths:
      - '**.cir'
      - '**.py'
      - '**.sh'

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install ngspice and python packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ngspice python3-numpy python3-matplotlib

    - name: Run simulation
      run: |
        chmod +x run_sim.sh
        ./run_sim.sh

    - name: Upload simulation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: simulation-results
        path: |
          output.csv
          output.raw
          plot.png
          sim.log
